CREATE TABLE ExerciseDefinition (
  Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Title NVARCHAR(255) NOT NULL,
  Unit VARCHAR(50) NOT NULL,
  UserId INT NOT NULL,
  FOREIGN KEY (UserId) REFERENCES User(Id)
);