CREATE TABLE User (
  Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  FirstName NVARCHAR(255) NOT NULL,
  LastName NVARCHAR(255) NOT NULL,
  Email NVARCHAR(255) NOT NULL,
  PasswordHash VARBINARY(64) NOT NULL,
  PasswordSalt VARBINARY(128) NOT NULL
);