services:
  robic.service:
    image: ${DOCKER_REGISTRY-}robicservice
    build:
      context: .
      dockerfile: Robic.Service/Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - 8080:8080
      - 8081:8081
    restart: always
  nginx:
    image: nginx:latest
    restart: always
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - certificates:/etc/letsencrypt/:rw
volumes:
  certificates:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./nginx/certificates
